import React, { memo, useRef, useState } from "react";
import { Camera, Settings, Smartphone, Monitor } from "lucide-react";
import { rankLabel } from "../game/gameEngine";

const SUIT_SYMBOL = { s: "♠", h: "♥", d: "♦", c: "♣" };
const SUIT_COLOR = { s: "#1E1A17", h: "#A12F3A", d: "#A12F3A", c: "#1E1A17" };

function avatarFallback(name){const text=(name||"?").trim();return text.slice(0,2).toUpperCase();}
const Avatar=memo(function Avatar({src,name,size=38,className=""}){return src?<img className={`avatar ${className}`} src={src} alt="" style={{width:size,height:size}}/>:<div className={`avatar avatar-fallback ${className}`} style={{width:size,height:size}}>{avatarFallback(name)}</div>;});
function compressAvatar(file){return new Promise((resolve,reject)=>{if(!file||!file.type.startsWith("image/"))return reject(new Error("请选择图片文件"));if(file.size>5*1024*1024)return reject(new Error("图片不能超过 5MB"));const reader=new FileReader();reader.onerror=()=>reject(new Error("图片读取失败"));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error("图片格式无法读取"));img.onload=()=>{const max=256,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale));const canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;const ctx=canvas.getContext("2d");ctx.drawImage(img,0,0,w,h);resolve(canvas.toDataURL("image/jpeg",0.82));};img.src=reader.result;};reader.readAsDataURL(file);});}
function AvatarPicker({avatar,username,onChange,size=38}){const inputRef=useRef(null);const [busy,setBusy]=useState(false),[error,setError]=useState("");const pick=async(e)=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;setError("");setBusy(true);try{const data=await compressAvatar(file);await onChange(data);}catch(err){setError(err.message||"头像设置失败");}finally{setBusy(false);}};return <div className="avatar-picker-wrap"><button type="button" className="avatar-picker" title="更换头像" onClick={()=>inputRef.current?.click()} disabled={busy}><Avatar src={avatar} name={username} size={size}/><span className="avatar-camera"><Camera size={12}/></span></button><input ref={inputRef} type="file" accept="image/*" onChange={pick} hidden/>{error&&<span className="avatar-error">{error}</span>}</div>;}
const PlayingCard=memo(function PlayingCard({card,hidden=false,small=false,delay=0}){if(hidden||!card)return <div className={`card ${small?"small":""} back`} style={{animationDelay:`${delay}ms`}}/>;const color=SUIT_COLOR[card.s];return <div className={`card ${small?"small":""} dealt`} style={{"--delay":`${delay}ms`,color}}><span className="card-rank">{rankLabel(card.r)}</span><span className="card-suit">{SUIT_SYMBOL[card.s]}</span></div>;});
function seatPosition(i,n){const angle=Math.PI*2*i/n-Math.PI/2,rx=44,ry=40;return{left:`${50+rx*Math.cos(angle)}%`,top:`${50+ry*Math.sin(angle)}%`};}
function OrientationSettings({orientation,setOrientation}){const [open,setOpen]=useState(false);const choose=value=>{setOrientation(value);localStorage.setItem("river-poker-orientation",value);setOpen(false);};return <div className="orientation-settings"><button className="orientation-settings-btn" type="button" title="显示设置" onClick={()=>setOpen(v=>!v)}><Settings size={17}/></button>{open&&<div className="orientation-menu"><div className="orientation-title">牌桌方向</div><button className={orientation==="portrait"?"active":""} onClick={()=>choose("portrait")}><Smartphone size={14}/>竖屏</button><button className={orientation==="landscape"?"active":""} onClick={()=>choose("landscape")}><Monitor size={14}/>横屏</button></div>}</div>;}

export { Avatar, AvatarPicker, PlayingCard, OrientationSettings, seatPosition };
